ALTER TABLE asset_wx_labels ALTER COLUMN label TYPE TEXT;

UPDATE asset_wx_labels SET label = UPPER(label);

DROP TYPE IF EXISTS asset_wx_label_value_type;

CREATE TABLE IF NOT EXISTS asset_labels (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY,
    superseded_by BIGINT DEFAULT 9223372036854775806 NOT NULL,
    block_uid BIGINT NOT NULL CONSTRAINT data_entries_block_uid_fkey REFERENCES blocks_microblocks (uid) ON DELETE CASCADE,
    asset_id TEXT NOT NULL,
    labels TEXT[] NOT NULL,
    PRIMARY KEY (superseded_by, asset_id)
);


CREATE OR REPLACE FUNCTION reopen_asset_labels() RETURNS VOID 
    language plpgsql 
AS $$
BEGIN
    UPDATE
        asset_labels
    SET
        superseded_by = 9223372036854775806
    WHERE
    uid IN (
        SELECT
            al1.uid
        FROM
            asset_labels al1
            LEFT JOIN asset_labels al2 ON al1.superseded_by = al2.uid
        WHERE
            al1.superseded_by != 9223372036854775806
            AND al2.uid IS NULL
    );
END;
$$;


CREATE OR REPLACE FUNCTION rollback_to(target_height INTEGER) RETURNS VOID 
    language plpgsql 
AS $$ 
BEGIN
    DELETE FROM blocks_microblocks WHERE height >= target_height;

    EXECUTE reopen_assets();
    EXECUTE reopen_asset_labels();
    EXECUTE reopen_data_entries();
    EXECUTE reopen_issuer_balances();
    EXECUTE reopen_out_leasings();
END;
$$;
