CREATE TABLE IF NOT EXISTS asset_names (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY,
    superseded_by BIGINT DEFAULT 9223372036854775806 NOT NULL,
    block_uid BIGINT NOT NULL CONSTRAINT asset_names_block_uid_fkey REFERENCES blocks_microblocks (uid) ON DELETE CASCADE,
    asset_id TEXT NOT NULL,
    asset_name TEXT NOT NULL,
    PRIMARY KEY (superseded_by, asset_id)
);
create index "asset_names_block_uid_idx" on asset_names(block_uid);

CREATE TABLE IF NOT EXISTS asset_descriptions (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY,
    superseded_by BIGINT DEFAULT 9223372036854775806 NOT NULL,
    block_uid BIGINT NOT NULL CONSTRAINT asset_descr_block_uid_fkey REFERENCES blocks_microblocks (uid) ON DELETE CASCADE,
    asset_id TEXT NOT NULL,
    asset_description TEXT NOT NULL,
    PRIMARY KEY (superseded_by, asset_id)
);
create index "asset_descr_block_uid_idx" on asset_descriptions(block_uid);

CREATE OR REPLACE FUNCTION reopen_asset_names() RETURNS VOID
    language plpgsql
AS $$
BEGIN
    UPDATE
        asset_names
    SET
        superseded_by = 9223372036854775806
    WHERE
    uid IN (
        SELECT
            al1.uid
        FROM
            asset_names al1
            LEFT JOIN asset_names al2 ON al1.superseded_by = al2.uid
        WHERE
            al1.superseded_by != 9223372036854775806
            AND al2.uid IS NULL
    );
END;
$$;

CREATE OR REPLACE FUNCTION reopen_asset_descriptions() RETURNS VOID
    language plpgsql
AS $$
BEGIN
    UPDATE
        asset_descriptions
    SET
        superseded_by = 9223372036854775806
    WHERE
    uid IN (
        SELECT
            al1.uid
        FROM
            asset_descriptions al1
            LEFT JOIN asset_descriptions al2 ON al1.superseded_by = al2.uid
        WHERE
            al1.superseded_by != 9223372036854775806
            AND al2.uid IS NULL
    );
END;
$$;


CREATE OR REPLACE FUNCTION rollback_to(target_height INTEGER) RETURNS VOID
    language plpgsql
AS $$
BEGIN
    DELETE FROM blocks_microblocks WHERE height >= target_height;

    EXECUTE reopen_assets();
    EXECUTE reopen_asset_labels();
    EXECUTE reopen_asset_tickers();
    EXECUTE reopen_asset_names();
    EXECUTE reopen_asset_descriptions();
    EXECUTE reopen_data_entries();
    EXECUTE reopen_issuer_balances();
    EXECUTE reopen_out_leasings();
END;
$$;
